// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvmuwwqmvmqhhymavlkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2bXV3d3Ftdm1xaGh5bWF2bGtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzAyNjgsImV4cCI6MjA2NTE0NjI2OH0.BQH-CiaCTu10pWt_2iuvyxJoOJo5atwP0gpEvnLgWvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);